# Generated by Django 3.1.5 on 2021-01-20 20:57

import config.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=config.utils.uuid_name_upload_to)),
                ('content', models.TextField()),
                ('interest', models.PositiveIntegerField()),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devtool', to='devtool.devtool')),
            ],
        ),
    ]
